version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://scdf_username:scdf_password@db:5432/scdf_db
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: scdf_username
      POSTGRES_PASSWORD: scdf_password
      POSTGRES_DB: scdf_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
